### ISSUE TITLE
Several DHCP on the same host and different interfaces

### ISSUE THREAD

**Issue by altSoftLLC** [krolaw/dhcp4#22]
ListenAndServeIf("eth0", handler)
ListenAndServeIf("eth1", handler)

Error:
listen udp4 :67: bind: address already in use

**Comment by krolaw** [comment]
Unfortunately, As per the comments for ListenAndServeIf:
// Serving DHCP over multiple interfaces will
// require your own dhcp4.ServeConn, as listening to broadcasts utilises all
// interfaces (so you cannot have more than on listener).

And as per Serve:
// To capture limited broadcast packets (sent to 255.255.255.255), you must
// listen on a socket bound to IP_ADDRANY (0.0.0.0). This means that broadcast
// packets sent to any interface on the system may be delivered to this
// socket.  See: **https://code.google.com/p/go/issues/detail?id=7106**
//
// Additionally, response packets may not return to the same
// interface that the request was received from.  Writing a custom ServeConn,
// or using ServeIf() can provide a workaround to this problem.

All up, you have found a documented problem (albeit not where it was needed in your case).  I haven't investigated solving it fully (as required for your case) as I haven't needed it.  That said, I would be happy to review your solution for inclusion in this project :-)

**Comment by krolaw** [comment]
Fixed with commit d72fa37.
