### ISSUE TITLE
next-server

### ISSUE THREAD

**Issue by omz-one** [krolaw/dhcp4#32]
Does not support next-server because siaddr not add to packet in ReplyPacket()

**Comment by krolaw** [comment]
You only set a "next server" if you have one.  You don't use the client value.

**Comment by xxxmailk** [comment]
> 
> 
> You only set a "next server" if you have one. You don't use the client value.

^_^, hi, can you tell me how to set a "next server", thanks

**Comment by krolaw** [comment]
I think you would add the next server option to the reply packet prior to responding.

**Comment by xxxmailk** [comment]
I've been add tftpsever & tftpfilename options in handler, but it's not useful.

**Comment by xxxmailk** [comment]
I've defined the tftp server address (option code 66) as 192.168.181.134, but client received tftp server name is 192.168.181.254 which capture by tcpdump and parse by wireshark @krolaw

**Comment by xxxmailk** [comment]
:) I used SetsiAddr() function and it's looks good. thank you very much. @krolaw
