### ISSUE TITLE
malformed dhcp option for DHCP server identifier

### ISSUE THREAD

**Issue by leslie-qiwa** [krolaw/dhcp4#44]
Seems like serverId variable has some random prefix which will show up when converting to []byte, then fill in the structure. https://github.com/krolaw/dhcp4/blob/master/packet.go#L179

Please take a look at this screen capture from Wireshark . IP is 127.0.0.1, which is 7f000001 and last 4 bytes.

<img width="1079" alt="screen shot 2018-11-02 at 3 37 19 pm" src="https://user-images.githubusercontent.com/34456213/47943814-3b4aba00-deb5-11e8-8f2f-e51285a8d951.png">

**Comment by leslie-qiwa** [comment]
Not sure if this is golang issue or not. But create one issue at https://github.com/golang/go/issues/28571 also.

**Comment by krolaw** [comment]
See: https://play.golang.org/p/GgCl3Byi0Uj

**Comment by leslie-qiwa** [comment]
I thought dhcp4 package can will change so that other people can avoid as well. But anyway, I'll add conversation at my side too. Thanks
