### ISSUE TITLE
Looking for new Maintainer

### ISSUE THREAD

**Issue by krolaw** [krolaw/dhcp4#46]
I no longer work on projects requiring DHCP and am therefore not suited to maintain this library. Anyone interested it taking over?

**Comment by vitalvas** [comment]
I'm use this library for my proprietary server for cloud.

**Comment by emmaly** [comment]
I'm interested, but I'm not sure if I have enough bandwidth to support it.  We certainly would not like to see this library fall into disrepair as we do use it.  I'll discuss this internally to see if this is something we'd be willing to take on.  If someone else that is motivated and qualified to take this on comes through, don't wait for me.

**Comment by vitalvas** [comment]
I have some time to maintain this library.

**Comment by krolaw** [comment]
Hi, sorry for the late reply, I wanted to wait at least a month to assess interest. Moving forward, I'm not sure if a transfer will break the import in existing Go projects. In the meantime, it might just be easier to make you both collaborators. Happy to discuss.

**Comment by krolaw** [comment]
2 collaborators should be plenty.
