### ISSUE TITLE
how to stop dhcp server?

### ISSUE THREAD

**Issue by Gictorbit** [krolaw/dhcp4#50]
I'm using this library in my project on linux and I need to run server within `goroutine` and stop it after, so how can I do this?
here is a sample of my code, also I'm trying to setup server on a virtual interface here

```go
pc, _ := conn.NewUDP4BoundListener(ifName, ":67")
go func() {
  if err := dhcp4.Serve(pc, handler); err != nil {
	  panic(err)
  }

}()
```

**Comment by krolaw** [comment]
Change the panic to return/break and close pc when ready is one way.

**Comment by Gictorbit** [comment]
wow thank you so much
